### ISSUE TITLE
Replace Gutenberg Editor with Block Editor

### ISSUE THREAD

**Issue by bph** [GutenbergHubOfficial/gutenberg-detector#1]
The block editor is the official term to identify the WYSIWYG editor in WordPress 
When you use the term Gutenberg Editor, lot of people think it's something outside of WordPress like Oxygen or Bricksy. If you hook into the WordPress built in block editor, you should also call it that. 

The Classic Editor plugin should be a role model, that also distinguish between block editor can classic editor and does not mention the term Gutenberg, 

Thanks for your consideration :-)

**Comment by munirkamal** [comment]
Thank you for your suggestion. I understand that "block editor" is now the official term, but it's worth noting that "Gutenberg" is also widely recognized as a term referring to the block editor. In fact, when conducting searches on Google and other platforms, people often use "Gutenberg" to refer to the block editor.

Furthermore, there are several instances where WordPress officially uses the term "Gutenberg," such as in the link (https://wordpress.org/gutenberg/) and in the demo content and meta.

While I acknowledge your point, I believe that retaining the term "Gutenberg" is appropriate since it is well-known and associated with the plugin's purpose. Therefore, I would prefer to keep it as it is.

**Comment by bph** [comment]
Well I guess you don't want to help alleviate the confusion.  The WordPress project only uses the term Gutenberg when it talks about the overall project or the feature plugin, not the editor itself.

**Comment by munirkamal** [comment]
It would be beneficial if the official sources could address this confusion. It appears that the term "Gutenberg" is still being used in many instances to refer to the editor. As I mentioned before, I provided an example in my previous response, and I here's a screenshot for reference.
<img width="917" alt="Screenshot 2023-07-15 at 5 24 23 PM" src="https://github.com/GutenbergHubOfficial/gutenberg-detector/assets/5817882/721e5509-5119-499f-b947-b4860e423feb">

**Comment by munirkamal** [comment]
Thank you for your suggestion, but in the context of this particular plugin, the terminology used is not a significant concern. This plugin is only a temporary experimental one and is not something I intend to maintain, as clearly stated in the readme.

**Comment by bph** [comment]
Fair enough. Continue. What ever you think is right.
